### ISSUE TITLE
Make device fields optional

### ISSUE THREAD

**Issue by JimOverholt** [cisco-open/cisco-catalyst-wan-sdk#196]
# Pull Request summary:
`/dataservice/system/device/vedges` does not returns all fields required for `Device `model

# Description of changes:
```
# Arrange
session = VMANAGE_MACHINE.create_session(provider_tenant=tenant)
device = session.api.devices.get().filter(uuid=software_vedge_uuid).single_or_default()
# Act
# TODO: Fix vmngclient
# decommission = DecommissionAction(session, device)
# decommission.execute()
# result = decommission.wait_for_completed()
# [FAIL] "TypeError in test case "mtt_device_life_cycle.test_decommission_software_vedge_provider_as_tenant" at subtest "decommission_software_vedge"[515]: 
# __init__() missing 3 required positional arguments: 'hostname', 'reachability', and 'local_system_ip'"
response = session.put(f"/dataservice/system/device/decommission/{device.uuid}")
if response.status_code != 200:
    return[False, f"Problem with decomission of {device.uuid} occurred"]
```

# Checklist:
- [X] Make sure to run pre-commit before committing changes
- [X] Make sure all checks have passed
- [X] PR description is clear and comprehensive
- [X] Mentioned the issue that this PR solves (if applicable)
- [X] Make sure you test the changes

**Comment by JimOverholt** [comment]
This issue was migrated from an old repository: https://github.com/CiscoDevNet/catalystwan/pull/427
