### ISSUE TITLE
Policies Configuration Guide Example - create groups of interest 

### ISSUE THREAD

**Issue by JimOverholt** [cisco-open/cisco-catalyst-wan-sdk#197]
# Pull Request summary:
Create example for Policy API UX1 in vmngclient based on:
https://www.cisco.com/c/en/us/td/docs/routers/sdwan/configuration/policies/vedge-20-x/policies-book/centralized-policy.html

# Description of changes:
## Part 1 - create groups of interest

# Checklist:
- [x] Make sure to run pre-commit before committing changes
- [x] Make sure all checks have passed
- [x] PR description is clear and comprehensive
- [x] Mentioned the issue that this PR solves (if applicable)
- [x] Make sure you test the changes
