### ISSUE TITLE
Subtasks handler in wait_for_completed

### ISSUE THREAD

**Issue by JimOverholt** [cisco-open/cisco-catalyst-wan-sdk#421]
# Pull Request summary:
- Add subtasks handler to wait_for_completed.
- Changed Existing API's methods using wait_for_completed, because wait_for_completed starts to returns TaskResult(bool, List[SubTaskData]) - bool is True if all subtasks are success, or returns False if at least one is failed
- Change exception blocks into conditional statements - no more looking for first element in list, so IndexError will not be raised
- Use custom exceptions instead of built-ins
- Use pydantic data model intsead attrs lib

# Checklist:
- [X] Make sure to run pre-commit before commiting changes
- [X] Make sure all checks have passed
- [X] PR description is clear and comprehensive
- [x] Mentioned the issue that this PR solves (if applicable)
- [X] Make sure you test the changes

**Comment by JimOverholt** [comment]
This issue was migrated from an old repository: https://github.com/CiscoDevNet/catalystwan/pull/190
